spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users-demo
    username: postgres
    password: febrero18
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update